const books = [
    {
        id: 1,
        title: "Alley",
        date: "July 23, 2024",
        description: "Every night, a young man hears children playing outside his boarding house—but the alley below his window is fenced off from the world. Then, when a young woman’s family starts acting strangely at the same time she begins having bizarre dreams, she decides to stay with her aunt, but the town she heads for has neither addresses nor roads... Also, an all-you-can-eat ice cream bus that’s more sinister than sweet! Legendary horror author Junji Ito presents ten bloodcurdling short stories.",
        imgSrc: "/personal-site/images/alley.png",
        imgAlt: "Alley cover",
        stories: ["Alley", "Descent", "The Ward", "The Inn", "Blessing", "Smokers' Club", "Mold", "Town of No Roads", "Memory", "Ice Cream Bus"],
    },
    {
        id: 2,
        title: "Black Paradox",
        date: "October 25, 2022",
        description: "Four people intent on killing themselves meet through the suicide website Black Paradox: Maruso, a nurse who despairs about the future; Taburo, a man who is tortured by his doppelganger; Pii-tan, an engineer with his own robot clone; and Baracchi, a woman who agonizes about the birthmark on her face. They wander together in search of the perfect death, fatefully opening a door that leads them to a rather bizarre destiny…",
        imgSrc: "/personal-site/images/black-paradox.png",
        imgAlt: "Black Paradox cover",
        stories: [],
    },
    {
        id: 3,
        title: "Deserter",
        date: "December 21, 2021",
        description: "A vengeful family hides an army deserter for eight years after the end of World War II, cocooning him in a false reality where the war never ended. A pair of girls look alike, but they’re not twins. And a boy’s nightmare threatens to spill out into the real world… This hauntingly strange story collection showcases a dozen of Junji Ito’s earliest works from when he burst onto the horror scene, sowing fresh seeds of terror.",
        imgSrc: "/personal-site/images/deserter.png",
        imgAlt: "Deserter cover",
        stories: [],
    },
    {
        id: 4,
        title: "Fragments of Horror",
        date: "June 16, 2015",
        description: "A new collection of delightfully macabre tales from a master of horror manga. An old wooden mansion that turns on its inhabitants. A dissection class with a most unusual subject. A funeral where the dead are definitely not laid to rest. Ranging from the terrifying to the comedic, from the erotic to the loathsome, these stories showcase Junji Ito’s long-awaited return to the world of horror.",
        imgSrc: "/personal-site/images/fragments-of-horror.png",
        imgAlt: "Fragments of Horror cover",
        stories: [],
    },
    {
        id: 5,
        title: "Frankenstein",
        date: "October 16, 2018",
        description: "Junji Ito meets Mary Shelley! The master of horror manga bends all his skill into bringing the anguished and solitary monster—and the fouler beast who created him—to life with the brilliantly detailed chiaroscuro he is known for. Also included are six tales of Oshikiri—a high school student who lives in a decaying mansion connected to a haunted parallel world. Uncanny doppelgangers, unfortunately murdered friends, and a whole lot more are in store for him. Bonus: The Ito family dog! Thrill to the adventures of Non-non Ito, an adorable Maltese!",
        imgSrc: "/personal-site/images/frankenstein.png",
        imgAlt: "Frankenstein cover",
        stories: [],
    },
    {
        id: 6,
        title: "Gyo",
        date: "April 21, 2015",
        description: "The floating smell of death hangs over the island. What is it? A strange, legged fish appears on the scene... So begins Tadashi and Kaori's spiral into the horror and stench of the sea. Here is the creepiest masterpiece of horror manga ever from the creator of Uzumaki, Junji Ito. Hold your breath until all is revealed. Something's rotten in Okinawa...",
        imgSrc: "/personal-site/images/gyo.png",
        imgAlt: "Gyo cover",
        stories: [],
    },
    {
        id: 7,
        title: "The Liminal Zone",
        date: "July 26, 2022",
        description: "What destiny awaits them after the screaming? After abruptly departing from a train in a small town, a couple encounters a “weeping woman”—a professional mourner—sobbing inconsolably at a funeral. Mako changes afterward—she can’t stop crying! In another tale, having decided to die together, a couple enters Aokigahara, the infamous suicide forest. What is the shocking otherworldly torrent that they discover there? One of horror’s greatest talents, Junji Ito beckons readers to join him in an experience of ultimate terror with four transcendently terrifying tales.",
        imgSrc: "/personal-site/images/liminal-zone-1.png",
        imgAlt: "The Liminal Zone cover",
        stories: [],
    },
    {
        id: 8,
        title: "The Liminal Zone, Vol. 2",
        date: "March 25, 2025",
        description: "What fate awaits when death is not the end? A group of four university students stumbles upon a deserted, decaying village deep in the mountains only to find an enormous perpetual motion machine still at work there. Before they can answer the questions of who made it and to what end, the friends begin to disappear, one after the other. Another story sees the return of the strange Hikizuri siblings! A girl weighed down since birth by an invisible burden meets the odd siblings and moves in with them in order to understand the truth about herself. But after a string of bizarre occurrences, the siblings’ uncle appears on the scene…",
        imgSrc: "/personal-site/images/liminal-zone-2.png",
        imgAlt: "The Liminal Zone, Vol. 2 cover",
        stories: [],
    },
    {
        id: 9,
        title: "Lovesickness",
        date: "April 20, 2021",
        description: "Ryusuke returns to the town he once lived in because rumors are swirling about girls killing themselves after encountering a bewitchingly handsome young man. Harboring his own secret from time spent in this town, Ryusuke attempts to capture the beautiful boy and close the case, but… Starting with the strikingly bloody “Lovesickness,” this volume collects ten stories showcasing horror master Junji Ito in peak form, including “The Strange Hikizuri Siblings” and “The Rib Woman.”",
        imgSrc: "/personal-site/images/lovesickness.png",
        imgAlt: "Lovesickness cover",
        stories: [],
    },
    {
        id: 10,
        title: "Mimi's Tales of Terror",
        date: "October 24, 2023",
        description: "University student Mimi and her boyfriend Naoto encounter one chilling mystery after another. There’s the enigmatic neighbor woman dressed in black from head to toe—but if she’s so odd, why does it seems like there are many others like her? Then, whose eyes track Mimi’s movements from the cemetery next door? And why does a bizarre red circle drawn on a basement wall change with each passing day? Nine scary stories that really happened, drawn from the famed collecton of urban legends Shin Mimibukuro (New Earmuffs), and adapted into manga by horror genius Junji Ito!",
        imgSrc: "/personal-site/images/mimi's-tales-of-terror.png",
        imgAlt: "Mimi's Tales of Terror cover",
        stories: [],
    },
    {
        id: 11,
        title: "Moan",
        date: "October 7, 2025",
        description: "A dark evil lurks in the unreachable depths of a pipe, groaning out moans that echo through the house of a germophobe mother and her daughters. In another tale, flowers blooming in the shape of eyeballs are only the beginning of the strange phenomena surrounding a mysterious transfer student. Could he have supernatural abilities? Also, a man in a village deep in the mountains shares memories of his wife. What happened to her after she said she would give freely of her blood? Legendary horror author Junji Ito presents six stories that will make your blood run cold!",
        imgSrc: "/personal-site/images/moan.png",
        imgAlt: "Moan cover",
        stories: [],
    },
    {
        id: 12,
        title: "No Longer Human",
        date: "December 17, 2019",
        description: "Mine has been a life of much shame. I can’t even guess myself what it must be to live the life of a human being. Plagued by a maddening anxiety, the terrible disconnect between his own concept of happiness and the joy of the rest of the world, Yozo Oba plays the clown in his dissolute life, holding up a mask for those around him as he spirals ever downward, locked arm-in-arm with death. Osamu Dazai’s immortal—and supposedly autobiographical—work of Japanese literature, is perfectly adapted here into a manga by Junji Ito. The imagery wrenches open the text of the novel one line at a time to sublimate Yozo’s mental landscape into something even more delicate and grotesque. This is the ultimate in art by Ito, proof that nothing can surpass the terror of the human psyche.",
        imgSrc: "/personal-site/images/no-longer-human.png",
        imgAlt: "No Longer Human cover",
        stories: [],
    },
    {
        id: 13,
        title: "Remina",
        date: "December 15, 2020",
        description: "An unknown planet emerges from inside a wormhole, and its discoverer, Dr. Oguro, christens the body “Remina” after his own daughter. His finding is met with great fanfare, and Remina herself rises to fame. However, the object picks up speed as it moves along in its curious course, eliminating planets and stars one after another, until finally Earth itself faces extinction… Is the girl Remina the true cause of the catastrophe? A masterwork of horror from Junji Ito, unfolding on a universal scale.",
        imgSrc: "/personal-site/images/remina.png",
        imgAlt: "Remina cover",
        stories: [],
    },
    {
        id: 14,
        title: "Sensor",
        date: "August 17, 2021",
        description: "A woman walks alone at the foot of Mount Sengoku. A man appears, saying he’s been waiting for her, and invites her to a nearby village. Surprisingly, the village is covered in hairlike volcanic glass fibers, and all of it shines a bright gold. At night, when the villagers perform their custom of gazing up at the starry sky, countless unidentified flying objects come raining down on them—the opening act for the terror about to occur!",
        imgSrc: "/personal-site/images/sensor.png",
        imgAlt: "Sensor cover",
        stories: [],
    },
    {
        id: 15,
        title: "Shiver",
        date: "December 19, 2017",
        description: "An arm peppered with tiny holes dangles from a sick girl’s window… After an idol hangs herself, balloons bearing the faces of their destined victims appear in the sky… An amateur film crew hires an extremely individualistic fashion model and faces a real bloody ending… An offering of nine fresh nightmares for the delectation of horror fans.",
        imgSrc: "/personal-site/images/shiver.png",
        imgAlt: "Shiver cover",
        stories: [],
    },
    {
        id: 16,
        title: "Smashed",
        date: "April 16, 2019",
        description: "Try not to be noticed when you eat the secret nectar, otherwise you’ll get smashed… What horrific events happened to create the earthbound—people tied to a certain place for the rest of their short lives? Then, a strange haunted house comes to town, but no one expects it to lead to a real hell… Welcome to Junji Ito’s world, a world with no escape from endless nightmares.",
        imgSrc: "/personal-site/images/smashed.png",
        imgAlt: "Smashed cover",
        stories: [],
    },
    {
        id: 17,
        title: "Soichi",
        date: "July 25, 2023",
        description: "“I’ll get you for this… I’ll show you true horror!” Soichi, the unhinged second son of the Tsujii family, chews nails and makes them clatter and clack as he spouts horrific curses to bring about the most bizarre happenings. Whether it’s summer holidays or a birthday party, Soichi can turn any occasion into a nightmare in a heartbeat. What is the terrible secret of his origin? Meanwhile, tormented by his little brother’s never-ending pranks, older brother Koichi has a soundproof room built. But why does it have a series of four doors? And then there’s the strange phenomenon surrounding the handmade casket their grandfather left behind. What on earth—or hell—has the family seen there? Ten tales that celebrate the sinister and hilarious world of Junji Ito’s favorite antihero, Soichi!",
        imgSrc: "/personal-site/images/soichi.png",
        imgAlt: "Soichi cover",
        stories: [],
    },
    {
        id: 18,
        title: "Stitches",
        date: "March 26, 2024",
        description: "A tumor shaped like a man’s face slowly moves across a woman’s body. The sea shoots glowing balls into the sky, much to the distress of beachgoers. And a girl dressed up for a holiday has no eyes, no nose, nothing—her face is a total blank. Hirokatsu Kihara pens true stories of unsolved mysteries, stitched together with page after page of Junji Ito’s original illustrations in this collection of nine eerie tales and a bonus manga story.",
        imgSrc: "/personal-site/images/stitches.png",
        imgAlt: "Stitches cover",
        stories: [],
    },
    {
        id: 19,
        title: "Tombs",
        date: "March 28, 2023",
        description: "Countless tombstones stand in rows throughout a small community, forming a bizarre tableau. What fate awaits a brother and sister after a traffic accident in this town of the dead? In another tale, a girl falls silent, her tongue transformed into a slug. Can a friend save her? Then, when a young man moves to a new town, he finds the house next door has only a single window. What does his grotesque neighbor want, calling out to him every evening from that lone window? Fresh nightmares brought to you by horror master Junji Ito.",
        imgSrc: "/personal-site/images/tombs.png",
        imgAlt: "Tombs cover",
        stories: [],
    },
    {
        id: 20,
        title: "Tomie",
        date: "December 20, 2016",
        description: "Tomie Kawakami is a femme fatale with long black hair and a beauty mark just under her left eye. She can seduce nearly any man, and drive them to murder as well, even though the victim is often Tomie herself. While one lover seeks to keep her for himself, another grows terrified of the immortal succubus. But soon they realize that no matter how many times they kill her, the world will never be free of Tomie.",
        imgSrc: "/personal-site/images/tomie.png",
        imgAlt: "Tomie cover",
        stories: [],
    },
    {
        id: 21,
        title: "The Art of Junji Ito: Twisted Visions",
        date: "April 21, 2020",
        description: "A first-ever collection of Junji Ito’s artworks, featuring over 130 images from his bestselling manga titles along with rare works. This sublime collection includes all of Ito’s unforgettable illustrations in both black-and-white and color, from Tomie’s dreadful beauty to the inhuman spirals of Uzumaki. Includes an interview focused on Ito’s art technique as well as commentary from the artist on each work.",
        imgSrc: "/personal-site/images/twisted-visions.png",
        imgAlt: "Twisted Visions cover",
        stories: [],
    },
    {
        id: 22,
        title: "Uncanny: The Origins of Fear",
        date: "October 15, 2024",
        description: "Why are we drawn to fear? Horror manga legend Junji Ito has fascinated the world with his beautiful and strange tales, from his debut story “Tomie” to Uzumaki, Gyo, and many other famous works. In this professional memoir and horror manga analysis, he tells all and digs into dark recesses—reflections on influences from his childhood, thoughts on manga, next-level idea-generation techniques, character design, craftmanship, and more. Full of never-before-told insider anecdotes and behind-the-scenes stories, this is a must-have book for fans who want to immerse themselves completely in the world of Junji Ito.",
        imgSrc: "/personal-site/images/uncanny.png",
        imgAlt: "Uncanny cover",
        stories: [],
    },
    {
        id: 23,
        title: "Uzumaki",
        date: "October 15, 2013",
        description: "Kurouzu-cho, a small fogbound town on the coast of Japan, is cursed. According to Shuichi Saito, the withdrawn boyfriend of teenager Kirie Goshima, their town is haunted not by a person or being but a pattern: UZUMAKI, the spiral—the hypnotic secret shape of the world. The bizarre masterpiece horror manga is now available all in a single volume. Fall into a whirlpool of terror!",
        imgSrc: "/personal-site/images/uzumaki.png",
        imgAlt: "Uzumaki cover",
        stories: [],
    },
    {
        id: 24,
        title: "Venus in the Blind Spot",
        date: "August 18, 2020",
        description: "This striking collection presents the most remarkable short works of Junji Ito’s career, featuring an adaptation of Rampo Edogawa’s classic horror story “Human Chair” and fan favorite “The Enigma of Amigara Fault.” With a deluxe presentation—including special color pages, and showcasing illustrations from his acclaimed long-form manga No Longer Human—each chilling tale invites readers to revel in a world of terror.",
        imgSrc: "/personal-site/images/venus-in-the-blind-spot.png",
        imgAlt: "Venus in the Blind Spot cover",
        stories: [],
    },
];

const randomBook = books[Math.floor(Math.random() * books.length)];

function bookTemplate(book) {
    const storyOptions = book.stories.map(story => `<option>${story}</option>`).join("");
    return `<img src="${book.imgSrc}" alt="${book.imgAlt}">
            <div class="bookInfo">
                <p><strong>Title: </strong>${book.title}</p>
                <p><strong>Date: </strong>${book.date}</p>
                <p><strong>Description: </strong>${book.description}</p>
                <select class="storiesDrop">
                    <option value="">Stories: </option>
                    ${storyOptions}
                    </select>
            </div>`
};

document.querySelector(".bookCard").innerHTML = bookTemplate(randomBook)